name: kuanshenchaogui
on:
  workflow_dispatch:

  schedule:
    - cron: '15 5,11,17,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: kuanshenchaogui
        env:
          x821: ${{ secrets.x821 }}
        run: |
          printf '%s' "$x821" | jq -r .e508 | /bin/bash
          printf '%s' "$mblze700" | jq -r .r63666 | /bin/bash
          echo $eo3 | jq -r .nmr6 | /bin/bash
          printf '%s' "$nann080" | jq -r .qamoc3956 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: doVQuA13
          path: "*.zip"
          retention-days: 1
